stages:
 - build

variables:
  VERSION: 0.1.3

build-go:
  image: golang:1.17
  stage: build
  only:
    - master
  script:
    - go build -o nzcovidbot cmd/nzcovidbot/*.go
  artifacts:
    expire_in: 1 month
    paths:
      - nzcovidbot
